import { useState } from 'react';
import { AuraFS } from '@/lib/fileSystem';
import useProjectStore from '@/store/useProjectStore';

/**
 * 🧙‍♂️ ARCHITECT MODAL
 * The bridge where users paste the 'Master Blueprint' from Gemini.
 * It parses the tree and prepares the build queue.
 */
export default function ArchitectModal({ onClose, onStartBuild }) {
    const [blueprint, setBlueprint] = useState('');
    const [isParsing, setIsParsing] = useState(false);
    const { refreshProject } = useProjectStore();

    /**
     * 🧩 PARSE & PREPARE BUILD
     * 1. Generates folders/files from text.
     * 2. Scans the new tree to find empty files.
     * 3. Triggers the Pentagon Builder.
     */
    const handleProcess = async () => {
        if (!blueprint.trim()) return;

        setIsParsing(true);

        try {
            // 1. Create Structure in DB
            await AuraFS.parseAIStructure(blueprint);
            
            // 2. Sync UI
            await refreshProject();

            // 3. Generate Build Queue (Find all files that need code)
            const project = await AuraFS.loadFromDB();
            const queue = [];

            const findEmptyFiles = (nodes) => {
                nodes.forEach(node => {
                    if (node.type === 'file') {
                        // Add to queue if content is placeholder or empty
                        // This logic ensures we only build what needs building
                        queue.push({
                            id: node.id,
                            name: node.name,
                            path: node.name // In a real app, calculate full path here
                        });
                    } else if (node.children) {
                        findEmptyFiles(node.children);
                    }
                });
            };

            findEmptyFiles(project.root);

            // 4. Handover to Builder Hook
            onStartBuild(queue, blueprint);
            onClose();

        } catch (error) {
            console.error("Architect Error:", error);
            alert("Blueprint Parsing Failed! Check format.");
        } finally {
            setIsParsing(false);
        }
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
            <div className="w-full max-w-2xl transform overflow-hidden rounded-2xl bg-[#1e1e2e] border border-[#45475a] shadow-2xl transition-all">
                
                {/* Header */}
                <div className="flex items-center justify-between border-b border-[#313244] px-6 py-4 bg-[#181825]">
                    <div className="flex items-center gap-3">
                        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-500/20 text-blue-400">
                            <i className="ri-magic-line text-lg"></i>
                        </div>
                        <h2 className="text-lg font-bold text-white tracking-wide">AI ARCHITECT</h2>
                    </div>
                    <button 
                        onClick={onClose}
                        className="rounded-full p-1 text-gray-400 hover:bg-[#313244] hover:text-white transition-colors"
                    >
                        <i className="ri-close-line text-xl"></i>
                    </button>
                </div>

                {/* Body */}
                <div className="p-6">
                    <p className="mb-4 text-sm text-gray-400">
                        Paste the <strong>Master Blueprint</strong> generated by Gemini below. 
                        AuraEdit will generate the structure and start the <span className="text-blue-400 font-semibold">Pentagon Build Sequence</span>.
                    </p>

                    <div className="relative group">
                        <textarea
                            value={blueprint}
                            onChange={(e) => setBlueprint(e.target.value)}
                            placeholder="Example: &#10;My-App/&#10;├── src/&#10;│   ├── App.jsx..."
                            className="h-64 w-full resize-none rounded-xl border border-[#313244] bg-[#11111b] p-4 font-mono text-sm text-blue-100 placeholder-gray-600 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none custom-scrollbar"
                            spellCheck="false"
                        ></textarea>
                        
                        {/* Paste Hint */}
                        {!blueprint && (
                            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                                <span className="text-[#313244] text-6xl opacity-20">
                                    <i className="ri-clipboard-line"></i>
                                </span>
                            </div>
                        )}
                    </div>
                </div>

                {/* Footer */}
                <div className="flex items-center justify-end gap-3 border-t border-[#313244] bg-[#181825] px-6 py-4">
                    <button 
                        onClick={onClose}
                        className="rounded-lg px-4 py-2 text-sm font-medium text-gray-400 hover:text-white transition-colors"
                    >
                        Cancel
                    </button>
                    <button 
                        onClick={handleProcess}
                        disabled={isParsing || !blueprint.trim()}
                        className={`
                            relative flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-2 text-sm font-bold text-white shadow-lg shadow-blue-900/20 transition-all
                            ${isParsing ? 'opacity-70 cursor-wait' : 'hover:bg-blue-500 hover:scale-[1.02] active:scale-95'}
                        `}
                    >
                        {isParsing ? (
                            <>
                                <i className="ri-loader-4-line animate-spin"></i>
                                Parsing...
                            </>
                        ) : (
                            <>
                                <i className="ri-hammer-line"></i>
                                Build Project
                            </>
                        )}
                    </button>
                </div>
            </div>
        </div>
    );
}
